### ISSUE TITLE
Server configuration

### ISSUE THREAD

**Issue by beeceej** [beeceej/iGo#14]
Should support configuring which port to listen on by:
- env var
- config file
- flag

precedence (lower number == higher precedence)
1. flag
2. env var
3. Config file

**Comment by sowmiyamuthuraman** [comment]
can i work on this?

**Comment by beeceej** [comment]
@sowmiyamuthuraman 
> can i work on this?

absolutely!

I was thinking:
the env vars would be prefixed like: `IGO_*`
the flag would just be `--port`
and in terms of linux/macos the config file would reside in `~/.config/igo/config.toml`.

I'm using port `:9999` as the default now, so if nothing in the config chain has been set we should probably default to that.

Let me know if you have any questions!
